### ISSUE TITLE
Can API Testing Libraries be added?

### ISSUE THREAD

**Issue by zac11** [atinfo/awesome-test-automation#142]
I have been working with API testing recently, with Postman. It is a great tool and has nice built in tools for testing the API's. However, I just discovered [postman-bdd](https://www.npmjs.com/package/postman-bdd), a comprehensive BDD style test-assertion library for Postman.
This library has made life a whole lot easier while testing the API's. Can this be added to any repository? I don't see any specific repository for API testing?

**Comment by zac11** [comment]
-

**Comment by polusok** [comment]
yes, i think postman can be added, need to think where

**Comment by zac11** [comment]
Can we create a separate section for API testing?

**Comment by polusok** [comment]
Do you have many tools to fill in if there is separate page? If it's just a few tools then it's pointless

**Comment by zac11** [comment]
I think I can list 4-5 of them - postman, SOAPUI, SOATest, TestMaker, vREST , Rapise.

**Comment by polusok** [comment]
ok, please make a pull request

**Comment by venkatramanareddy** [comment]
#190 Added a couple of REST API automation frameworks. Are there any changes required?
