### ISSUE TITLE
Add seleniumbase to frameworks - python

### ISSUE THREAD

**Issue by O2F** [atinfo/awesome-test-automation#206]
Hello,

I think seleniumbase is also a good candidate to be added to the frameworks you have.

More info here: https://github.com/seleniumbase/SeleniumBase

See if you agree also.

O2F

**Comment by polusok** [comment]
please make a pull request to https://github.com/atinfo/awesome-test-automation/blob/master/python-test-automation.md#web-ui-test-automation

**Comment by Amit-A** [comment]
Someone close this issue
