### ISSUE TITLE
Biltz.io goes to spirent cyberflood. 

### ISSUE THREAD

**Issue by dono-greeff** [atinfo/awesome-test-automation#330]
The tool is no longer blitz.io and appears to be part of cyberflood. If you follow the link you will see what I mean.

**Comment by poliarush** [comment]
please make pull request to remove broken links, thanks

**Comment by dono-greeff** [comment]
So its not so much a broken link. I think it needs someone to evaluate the new tool that has incorporated it. 

Or... Remove the link and suggestion all together. I will create a pull request to do the latter as I have no experience with cyberflood.

**Comment by dono-greeff** [comment]
Linked to https://github.com/atinfo/awesome-test-automation/pull/331 for review
