### ISSUE TITLE
Pyhton->Performance->Multi-Mechanize: Invalid link

### ISSUE THREAD

**Issue by dr29bart** [atinfo/awesome-test-automation#360]
http://testutils.org/multi-mechanize/
leads to 404 kind of page:
![image](https://user-images.githubusercontent.com/1547167/74229405-f6721d80-4cca-11ea-8631-faa1f8e13fac.png)

please, remove or update

**Comment by dc-avasilev** [comment]
http://multi-mechanize.readthedocs.io/en/latest/

**Comment by poliarush** [comment]
@dr29bart @dc-avasilev please make a pull request, much appreciated!
