### ISSUE TITLE
Add awesome and awesome-list topics to this repository

### ISSUE THREAD

**Issue by ASaiAnudeep** [atinfo/awesome-test-automation#412]
> Topics are labels that create subject-based connections between GitHub repositories and let you explore projects by type, technology, and more.

To make this repository more reachable, add `awesome` and `awesome-list` topics.

**Comment by poliarush** [comment]
What do you mean by add topics? Please explain

**Comment by ASaiAnudeep** [comment]
You can find more details on adding topics here - https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

> To help other people find and contribute to your project, you can add topics to your repository related to your project's intended purpose, subject area, affinity groups, or other important qualities.

As this repository is a curated list of awesome test automation frameworks, it would be great if we add `awesome` and `awesome-list` to the existing list of topics. These kind of projects are mostly tagged with `awesome` and `awesome-list` topics.

**Comment by poliarush** [comment]
done
