### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [atinfo/awesome-test-automation#467]
Hello, I found some broken hyperlinks:
- [ ] http://satisfy.tapack.io (file: java-test-automation.md, error: ENOTFOUND)
- [ ] http://qaprosoft.github.io/carina/ (file: java-test-automation.md, status code: 404)
- [ ] https://github.com/ObjectivityLtd/crux (file: java-test-automation.md, status code: 404)
- [ ] https://continuumsecurity.net/bdd-security/ (file: java-test-automation.md, status code: 404)
- [ ] https://www.thundra.io/foresight (file: java-test-automation.md, error: ENOTFOUND)
- [ ] http://qaprosoft.github.io/zafira/ (file: java-test-automation.md, status code: 404)
- [ ] https://netbeans.org/features/index.html (file: java-test-automation.md, status code: 404)
- [ ] http://www.icegreen.com/greenmail/ (file: java-test-automation.md, error: ECONNRESET)
- [ ] http://thucydides.info/docs/thucydides-one-page/thucydides.html (file: java-test-automation.md, status code: 404)
---
- [ ] https://www.scanmyserver.com/ (file: automation-and-testing-as-service.md, error: ECONNRESET)
- [ ] http://graphs.mozilla.org/graph.html (file: automation-and-testing-as-service.md, error: ENOTFOUND)

---

- [ ] https://macacajs.com/ (file: javascript-test-automation.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [ ] https://github.com/substack/stream-handbook (file: javascript-test-automation.md, status code: 404)
- [ ] http://blanketjs.org/ (file: javascript-test-automation.md, error: EAI_AGAIN)
- [ ] http://usejsdoc.org/ (file: javascript-test-automation.md, error: EAI_AGAIN)

---
- [ ] http://www8.hp.com/us/en/software-solutions/unified-functional-automated-testing/index.html (file: general-purpose-test-automation-tools.md, status code: 404)

---
- [ ] https://macacajs.com/ (file: mobile-test-automation.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
---
- [ ] http://thornag.github.io/php-vfs/ (file: php-test-automation.md, status code: 404)
- [ ] http://security.sensiolabs.org/ (file: php-test-automation.md, error: EAI_AGAIN)
- [ ] https://sismo.symfony.com/ (file: php-test-automation.md, error: ECONNREFUSED)
- [ ] http://cs.sensiolabs.org/ (file: php-test-automation.md, error: EAI_AGAIN)

---
- [ ] http://plugincompat.herokuapp.com/ (file: python-test-automation.md, status code: 503)
- [ ] http://twistedmatrix.com/trac/wiki/TwistedTrial (file: python-test-automation.md, status code: 404)
- [ ] http://www.logilab.org/project/logilab-common/ (file: python-test-automation.md, status code: 404)
- [ ] http://falcao.it/HTTPretty/ (file: python-test-automation.md, error: CERT_HAS_EXPIRED)
- [ ] http://www.joke2k.net/faker/ (file: python-test-automation.md, status code: 404)
- [ ] http://kahunacohen.com/2014/12/03/new-testing-paradigm-robotframework-pageobjects/ (file: python-test-automation.md, error: ENOTFOUND)
- [ ] https://github.com/Skyscanner/pages (file: python-test-automation.md, status code: 404)
- [ ] http://pywinauto.github.io/ (file: python-test-automation.md, status code: 404)
- [ ] http://scastillo.github.com/siesta (file: python-test-automation.md, status code: 404)
- [ ] http://fitzgen.github.io/pycco/ (file: python-test-automation.md, status code: 404)
- [ ] http://bitbucket.org/haard/gitapi (file: python-test-automation.md, status code: 404)
- [ ] https://www.chuancong.site/extratools/ (file: python-test-automation.md, error: ECONNRESET)

---

- [ ] http://cukes.info/ (file: ruby-test-automation.md, error: EAI_AGAIN)
- [ ] http://selenium.googlecode.com/git/docs/api/rb/index.html (file: ruby-test-automation.md, status code: 404)
- [ ] https://github.com/chemistrykit/chemistrykit (file: ruby-test-automation.md, status code: 404)
- [ ] http://rubyinstaller.org/add-ons/pik/ (file: ruby-test-automation.md, status code: 404)
- [ ] https://yandex.ru/dev/tank/ (file: ruby-test-automation.md, status code: 404)

**Comment by pyuscherbakov** [comment]
@poliarush Hi! You can close this issue. I'm resolved this in #485 #486
