### ISSUE TITLE
add TestComplete

### ISSUE THREAD

**Issue by yavlanskiy** [atinfo/awesome-test-automation#67]
It would be nice to add TestComplete, I do not see it in the list. But where to add ?, It supports 5 languages and all scripts.

**Comment by polusok** [comment]
Let's keep conversation in english so other english speaking people can join conversation.
So regarding TestComplete, honestly i don't know where to put it also.
There are a separate class of test automation tools - let's call it General Purpose like QTP, TestComplete, Ranorex, etc. that may be added to each language. However, it may be it's not good idea. It may be need to create separate file like https://github.com/atinfo/awesome-test-automation/blob/master/automation-and-testing-as-service.md where we will outline all good general purpose test automation tools. What do you think?

**Comment by vygidor** [comment]
**General Purpose** is a good name for this entirely new category. All the named tools are literally general, a lot of them are commercial products and are considered as "all-in-one" software (depends on perception ofc) or related to another products from the same company (as for example QTP is now named UFT [incuding the old HP Service Test] used for functional testing, where HP Loadrunner is for performance and load testing).

**Comment by yavlanskiy** [comment]
I agree. It is better to create a separate category.
What do you think, should not create a new category for REST API?

**Comment by polusok** [comment]
However, there are no too much general purpose tools to create separate file. What is your suggestion?

**Comment by yavlanskiy** [comment]
In that case, let's create a separate item for each language!?

**Comment by polusok** [comment]
added new files for universal tools https://github.com/atinfo/awesome-test-automation/blob/master/general-purpose-test-automation-tools.md
